metadata:
  engine: 4.0.2
  version: 0.1
  author: Ryan, Erik, Austin, Will
  company: BYU IEEE 2023-2024
units:
  kx: cx
  ky: cy
  capsx: 16.5
  capsy: 16.5
  default_spread: cx
  px: capsx-2
  py: capsy-2
  ledy: 5 - (cx/2)
points:
  zones:
    matrix:
      key:
        padding: cy * 1.2
        spread: cx * 1.2
      columns:
        function:
          key:
            rotate: -1
            column_net: P3
        pinky:
          key:
            splay: -3
            stagger: 3
            rotate: -1
            column_net: P4
        ring:
          key:
            splay: -5
            stagger: 8
            column_net: P5
        middle:
          key:
            splay: -5
            stagger: 3
            column_net: P6
        pointer:
          key:
            splay: -5
            stagger: -3
            rotate: 1
            column_net: P15
        inner:
          key:
            splay: -3
            stagger: -5
            rotate: 1
            column_net: P18
        macro:
          key:
            splay: -3
            stagger: -3
            rotate: 1
            spread: cx * 1.5
            column_net: P19
      rows:
        bottom:
          row_net: P14
        main:
          row_net: P16
        top:
          row_net: P7
        numbers:
          row_net: P8
    thumb:
      key:
        padding: cy * 1.2
        spread: cy * 1.2
      anchor:
        rotate: -15
        ref: matrix_macro_bottom
        shift: [-30, -45]
      rows:
        1:
          row_net: P14
        2:
          row_net: P16
      columns:
        1:
          key.column_net: P2
        2:
<<<<<<< HEAD:config.yaml
=======
          key.column_net: P21
>>>>>>> 9357610e44a2e8f6ba388603f1c14285e4b9d184:Keyboard.yaml
outlines:
  keys:
  - what: rectangle
    where: true
    size: [cx,cy]
  keycaps:
  - what: rectangle
    where: true
<<<<<<< HEAD:config.yaml
    size: [cx, cy]
=======
    size: [capsx, capsy]
>>>>>>> 9357610e44a2e8f6ba388603f1c14285e4b9d184:Keyboard.yaml
  board:
  - what: polygon
    operation: stack
    fillet: 10
    points:
    - ref: matrix_function_bottom
      shift: [-px,-py]
    - ref: matrix_function_numbers
      shift: [-px, py]
    - ref: matrix_pinky_numbers
      shift: [0, py]
    - ref: matrix_ring_numbers
      shift: [0, py]
    - ref: matrix_middle_numbers
      shift: [0, py]
    - ref: matrix_pointer_numbers
      shift: [0, py]
    - ref: matrix_inner_numbers
      shift: [0, py]
    - ref: matrix_macro_numbers
      shift: [px, py]
    - ref: matrix_macro_bottom
      shift: [px+5, -18]
    - ref: thumb_2_1
      shift: [px, -py]
    - ref: thumb_1_1
      shift: [-px, -py]
  panel:
  - name: board
  - operation: subtract
    name: keycaps
pcbs:
  boardPcb:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: True
        params:
          keycaps: True
          reverse: True
          hotswap: True
          from: "{{column_net}}"
          to: "{{colrow}}"
      
      switch_via:
        what: via
        where: true
        params:
          net: "{{column_net}}"
        adjust:
          shift: [0, cy/2]

      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [cy/2 -.7, -3]
          rotate: 90
      
      microcontroller:
        what: promicro
        params:
          orientation: "down"
<<<<<<< HEAD:config.yaml
=======
          P1: 'RAW'
          P0: 'GND'
>>>>>>> 9357610e44a2e8f6ba388603f1c14285e4b9d184:Keyboard.yaml
        where:
          ref: matrix_function_bottom
          shift: [2px, -py-2]

<<<<<<< HEAD:config.yaml
      rgbB:
        what: rgb
        params:
          side: "B"
          din: "din"
          dout: "dout"
        where: true
        adjust:
          shift: [0, ledy]

      rgbF:
        what: rgb
        params:
          side: "F"
          din: "din"
          dout: "dout"
        where: true
        adjust:
          shift: [0, ledy]
=======
      connector:
        what: trrs
        params:
          A: "VCC"
          B: "GND"
          C: "P9"
          D: "P10"
          reverse: true
        where:
          ref: matrix_macro_bottom
          shift: [-2,-px]
          rotate: 270
>>>>>>> 9357610e44a2e8f6ba388603f1c14285e4b9d184:Keyboard.yaml
